### ISSUE TITLE
Add resources

### ISSUE THREAD

**Issue by jenniferlindberg** [andnil5/dd2480-grp12-assignment2#4]
In this issue we link resources relevant for understanding the different **technologies** of the project.

**Comment by jenniferlindberg** [comment]
**Youtube** 📽️ 

- [_Creating CI/CD Pipeline using GitHub Actions for Python Project (Heroku Deployment Example)_](https://www.youtube.com/watch?v=WTofttoD2xg)

**Comment by andnil5** [comment]
Youtube 🎥 
[Python: Create Github Webhook and POST info to a Flask WebApp (ngrok)](https://www.youtube.com/watch?v=YMBzb_RBDAA)

Great inital skeleton for the flask server and working with github webhooks.

**Comment by andnil5** [comment]
**GitHub Docs 📖** 

- [Workflow of a GitHub CI server](https://docs.github.com/en/rest/guides/building-a-ci-server)

It gives a nice description of the workflow when building a custom CI server.

**Comment by majate** [comment]
**The requests-mock library** 📚 
- [Good example](https://mydeveloperplanet.com/2020/03/11/how-to-mock-a-rest-api-in-python/)
- [Documentation](https://requests-mock.readthedocs.io/en/latest/overview.html)

**Comment by jenniferlindberg** [comment]
This issue has been used for collecting resources during the course of the project, we now consider this finished.
