### ISSUE TITLE
Make the CI server import the correct version of modules

### ISSUE THREAD

**Issue by majate** [andnil5/dd2480-grp12-assignment2#40]
When the CI server has a copy of the repo inside the repo, we have two implementations of the `src` package which creates a name conflict. When the CI server tries to run the tests within the repo copy, the test files sometimes accidently import the wrong implementation of src (e.g `<this repo>/src/status_response.py` is imported as `src.status_response` instead of `<this repo>/git_repo/src/status_response.py`).

**Comment by majate** [comment]
A potential solution is to remove the `__init__.py` file from the root directory, rewrite all imports from `<module name>` to `src.<module name>`. This  will make it impossible to start the server with the script `python src/server` but will instead make it possible to run the server as `python -m src.server`

**Comment by omidhzr** [comment]
I was scratching my head on how we should go about fixing this issue with imports, if you have tested it out then I think we can do it! :)
